import 'country_code.dart';

class CountryData {
  static const List<CountryCode> countries = [
    CountryCode(name: 'United States', code: 'US', dialCode: '+1'),
    CountryCode(name: 'India', code: 'IN', dialCode: '+91'),
    CountryCode(name: 'United Kingdom', code: 'GB', dialCode: '+44'),
    CountryCode(name: 'Canada', code: 'CA', dialCode: '+1'),
    CountryCode(name: 'Australia', code: 'AU', dialCode: '+61'),
    CountryCode(name: 'Germany', code: 'DE', dialCode: '+49'),
    CountryCode(name: 'France', code: 'FR', dialCode: '+33'),
    CountryCode(name: 'Japan', code: 'JP', dialCode: '+81'),
    CountryCode(name: 'China', code: 'CN', dialCode: '+86'),
    CountryCode(name: 'Brazil', code: 'BR', dialCode: '+55'),
    CountryCode(name: 'Russia', code: 'RU', dialCode: '+7'),
    CountryCode(name: 'South Korea', code: 'KR', dialCode: '+82'),
    CountryCode(name: 'Italy', code: 'IT', dialCode: '+39'),
    CountryCode(name: 'Spain', code: 'ES', dialCode: '+34'),
    CountryCode(name: 'Netherlands', code: 'NL', dialCode: '+31'),
    CountryCode(name: 'Sweden', code: 'SE', dialCode: '+46'),
    CountryCode(name: 'Norway', code: 'NO', dialCode: '+47'),
    CountryCode(name: 'Denmark', code: 'DK', dialCode: '+45'),
    CountryCode(name: 'Finland', code: 'FI', dialCode: '+358'),
    CountryCode(name: 'Switzerland', code: 'CH', dialCode: '+41'),
    CountryCode(name: 'Austria', code: 'AT', dialCode: '+43'),
    CountryCode(name: 'Belgium', code: 'BE', dialCode: '+32'),
    CountryCode(name: 'Poland', code: 'PL', dialCode: '+48'),
    CountryCode(name: 'Czech Republic', code: 'CZ', dialCode: '+420'),
    CountryCode(name: 'Hungary', code: 'HU', dialCode: '+36'),
    CountryCode(name: 'Romania', code: 'RO', dialCode: '+40'),
    CountryCode(name: 'Bulgaria', code: 'BG', dialCode: '+359'),
    CountryCode(name: 'Croatia', code: 'HR', dialCode: '+385'),
    CountryCode(name: 'Slovenia', code: 'SI', dialCode: '+386'),
    CountryCode(name: 'Slovakia', code: 'SK', dialCode: '+421'),
    CountryCode(name: 'Estonia', code: 'EE', dialCode: '+372'),
    CountryCode(name: 'Latvia', code: 'LV', dialCode: '+371'),
    CountryCode(name: 'Lithuania', code: 'LT', dialCode: '+370'),
    CountryCode(name: 'Ireland', code: 'IE', dialCode: '+353'),
    CountryCode(name: 'Portugal', code: 'PT', dialCode: '+351'),
    CountryCode(name: 'Greece', code: 'GR', dialCode: '+30'),
    CountryCode(name: 'Cyprus', code: 'CY', dialCode: '+357'),
    CountryCode(name: 'Malta', code: 'MT', dialCode: '+356'),
    CountryCode(name: 'Luxembourg', code: 'LU', dialCode: '+352'),
    CountryCode(name: 'Iceland', code: 'IS', dialCode: '+354'),
    CountryCode(name: 'Liechtenstein', code: 'LI', dialCode: '+423'),
    CountryCode(name: 'Monaco', code: 'MC', dialCode: '+377'),
    CountryCode(name: 'San Marino', code: 'SM', dialCode: '+378'),
    CountryCode(name: 'Vatican City', code: 'VA', dialCode: '+379'),
    CountryCode(name: 'Andorra', code: 'AD', dialCode: '+376'),
    CountryCode(name: 'South Africa', code: 'ZA', dialCode: '+27'),
    CountryCode(name: 'Egypt', code: 'EG', dialCode: '+20'),
    CountryCode(name: 'Nigeria', code: 'NG', dialCode: '+234'),
    CountryCode(name: 'Kenya', code: 'KE', dialCode: '+254'),
    CountryCode(name: 'Morocco', code: 'MA', dialCode: '+212'),
    CountryCode(name: 'Tunisia', code: 'TN', dialCode: '+216'),
    CountryCode(name: 'Algeria', code: 'DZ', dialCode: '+213'),
    CountryCode(name: 'Libya', code: 'LY', dialCode: '+218'),
    CountryCode(name: 'Sudan', code: 'SD', dialCode: '+249'),
    CountryCode(name: 'Ethiopia', code: 'ET', dialCode: '+251'),
    CountryCode(name: 'Ghana', code: 'GH', dialCode: '+233'),
    CountryCode(name: 'Senegal', code: 'SN', dialCode: '+221'),
    CountryCode(name: 'Ivory Coast', code: 'CI', dialCode: '+225'),
    CountryCode(name: 'Cameroon', code: 'CM', dialCode: '+237'),
    CountryCode(name: 'Angola', code: 'AO', dialCode: '+244'),
    CountryCode(name: 'Mozambique', code: 'MZ', dialCode: '+258'),
    CountryCode(name: 'Madagascar', code: 'MG', dialCode: '+261'),
    CountryCode(name: 'Tanzania', code: 'TZ', dialCode: '+255'),
    CountryCode(name: 'Uganda', code: 'UG', dialCode: '+256'),
    CountryCode(name: 'Rwanda', code: 'RW', dialCode: '+250'),
    CountryCode(name: 'Burundi', code: 'BI', dialCode: '+257'),
    CountryCode(name: 'Malawi', code: 'MW', dialCode: '+265'),
    CountryCode(name: 'Zambia', code: 'ZM', dialCode: '+260'),
    CountryCode(name: 'Zimbabwe', code: 'ZW', dialCode: '+263'),
    CountryCode(name: 'Botswana', code: 'BW', dialCode: '+267'),
    CountryCode(name: 'Namibia', code: 'NA', dialCode: '+264'),
    CountryCode(name: 'Lesotho', code: 'LS', dialCode: '+266'),
    CountryCode(name: 'Swaziland', code: 'SZ', dialCode: '+268'),
    CountryCode(name: 'Mauritius', code: 'MU', dialCode: '+230'),
    CountryCode(name: 'Seychelles', code: 'SC', dialCode: '+248'),
    CountryCode(name: 'Comoros', code: 'KM', dialCode: '+269'),
    CountryCode(name: 'Djibouti', code: 'DJ', dialCode: '+253'),
    CountryCode(name: 'Somalia', code: 'SO', dialCode: '+252'),
    CountryCode(name: 'Eritrea', code: 'ER', dialCode: '+291'),
    CountryCode(name: 'Chad', code: 'TD', dialCode: '+235'),
    CountryCode(name: 'Central African Republic', code: 'CF', dialCode: '+236'),
    CountryCode(name: 'Democratic Republic of Congo', code: 'CD', dialCode: '+243'),
    CountryCode(name: 'Republic of Congo', code: 'CG', dialCode: '+242'),
    CountryCode(name: 'Gabon', code: 'GA', dialCode: '+241'),
    CountryCode(name: 'Equatorial Guinea', code: 'GQ', dialCode: '+240'),
    CountryCode(name: 'São Tomé and Príncipe', code: 'ST', dialCode: '+239'),
    CountryCode(name: 'Guinea', code: 'GN', dialCode: '+224'),
    CountryCode(name: 'Guinea-Bissau', code: 'GW', dialCode: '+245'),
    CountryCode(name: 'Sierra Leone', code: 'SL', dialCode: '+232'),
    CountryCode(name: 'Liberia', code: 'LR', dialCode: '+231'),
    CountryCode(name: 'Mali', code: 'ML', dialCode: '+223'),
    CountryCode(name: 'Burkina Faso', code: 'BF', dialCode: '+226'),
    CountryCode(name: 'Niger', code: 'NE', dialCode: '+227'),
    CountryCode(name: 'Benin', code: 'BJ', dialCode: '+229'),
    CountryCode(name: 'Togo', code: 'TG', dialCode: '+228'),
    CountryCode(name: 'Gambia', code: 'GM', dialCode: '+220'),
    CountryCode(name: 'Cape Verde', code: 'CV', dialCode: '+238'),
  ];
}
